### ISSUE TITLE
num_guilds and num_members presence templates return wrong values for sharded bots

### ISSUE THREAD

**Issue by L0SER8228** [greencoast-studios/discord.js-extended#33]
#### :bug: Describe the Bug

> currently, if we set the presence template `{num_guilds}`, it's showing only one shard guilds. 

#### :pencil2: Steps to Reproduce
> Add something so that it's show total guild count and user count for sharded bot too.
 
#### :confused: Expected Behavior

> A description of what you expected to get (if applicable).

#### :scroll: Log

``` text
Paste a relevant portion of the console log here.
```

#### :camera: Screenshots

> Paste a screenshot of the bug (if applicable).

#### :question: Other Information

* Node Version: `14.x.`
* Discord.js Version: `12.5.3.`

**Comment by moonstar-x** [comment]
Hey there!

Indeed this does happen not only for `{num_guilds}` but with `{num_members}` too.

Currently we're a bit busy with college and work and I can offer you to work on this in about a month from now since we actually need to do some updates to this lib in a specific order.

Thanks again for the report and sorry for any inconveniences caused! :)

**Comment by moonstar-x** [comment]
Fixed in #37.
